apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/yagachill/docker-lab:4b7d4818d5e4a48dca6da8af96f9944d3463294a
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
