apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/yagachill/docker-lab:ac58af1485c8594f0c3473b84c5d7e81d232cab5
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
