apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/yagachill/docker-lab:6a101f45c8a966e72e5361ea2a1768ae3a681a9b
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
