apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/yagachill/docker-lab:311086e653ecc993a1540d95f67bd86cf7c93944
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
