apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/yagachill/docker-lab:6d22527d2137d011c1bfff725bae5c8686e363ca
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
